-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Bagheera.Mutation exposing (..)

import Bagheera.InputObject
import Bagheera.Object
import Bagheera.Scalar
import Bagheera.ScalarCodecs
import Graphql.Internal.Builder.Argument as Argument
import Graphql.Internal.Builder.Object as Object
import Graphql.Operation exposing (RootMutation)
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


type alias CreateLinkRequiredArguments =
    { input : Bagheera.InputObject.CreateLinkInput }


{-| Create a new link
-}
createLink :
    CreateLinkRequiredArguments
    -> SelectionSet decodesTo Bagheera.Object.Link
    -> SelectionSet (Maybe decodesTo) RootMutation
createLink requiredArgs____ object____ =
    Object.selectionForCompositeField "createLink" [ Argument.required "input" requiredArgs____.input Bagheera.InputObject.encodeCreateLinkInput ] object____ (Basics.identity >> Decode.nullable)


type alias DeleteLinkRequiredArguments =
    { id : Bagheera.ScalarCodecs.Id }


{-| Delete a link
-}
deleteLink :
    DeleteLinkRequiredArguments
    -> SelectionSet decodesTo Bagheera.Object.Link
    -> SelectionSet (Maybe decodesTo) RootMutation
deleteLink requiredArgs____ object____ =
    Object.selectionForCompositeField "deleteLink" [ Argument.required "id" requiredArgs____.id (Bagheera.ScalarCodecs.codecs |> Bagheera.Scalar.unwrapEncoder .codecId) ] object____ (Basics.identity >> Decode.nullable)


type alias UpdateLinkRequiredArguments =
    { input : Bagheera.InputObject.UpdateLinkInput }


{-| Update a link
-}
updateLink :
    UpdateLinkRequiredArguments
    -> SelectionSet decodesTo Bagheera.Object.Link
    -> SelectionSet (Maybe decodesTo) RootMutation
updateLink requiredArgs____ object____ =
    Object.selectionForCompositeField "updateLink" [ Argument.required "input" requiredArgs____.input Bagheera.InputObject.encodeUpdateLinkInput ] object____ (Basics.identity >> Decode.nullable)
