-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Bagheera.Object exposing (..)


type Link
    = Link


type LinkConnection
    = LinkConnection


type LinkEdge
    = LinkEdge


type PageInfo
    = PageInfo
