-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Bagheera.ScalarCodecs exposing (..)

import Bagheera.Scalar exposing (defaultCodecs)


type alias Id =
    Bagheera.Scalar.Id


type alias LinkId =
    Bagheera.Scalar.LinkId


codecs : Bagheera.Scalar.Codecs Id LinkId
codecs =
    Bagheera.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        , codecLinkId = defaultCodecs.codecLinkId
        }
