-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Bagheera.Object.LinkEdge exposing (..)

import Bagheera.Object
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| A cursor for use in pagination
-}
cursor : SelectionSet String Bagheera.Object.LinkEdge
cursor =
    Object.selectionForField "String" "cursor" [] Decode.string


{-| The item at the end of the edge
-}
node :
    SelectionSet decodesTo Bagheera.Object.Link
    -> SelectionSet (Maybe decodesTo) Bagheera.Object.LinkEdge
node object____ =
    Object.selectionForCompositeField "node" [] object____ (Basics.identity >> Decode.nullable)
