-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Bagheera.Object.Link exposing (..)

import Bagheera.Object
import Bagheera.Scalar
import Bagheera.ScalarCodecs
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Auto-generated hash for the shortened URL
-}
hash : SelectionSet String Bagheera.Object.Link
hash =
    Object.selectionForField "String" "hash" [] Decode.string


{-| Number of times a link has been viewed
-}
hits : SelectionSet (Maybe Int) Bagheera.Object.Link
hits =
    Object.selectionForField "(Maybe Int)" "hits" [] (Decode.int |> Decode.nullable)


{-| The ID of an object
-}
id : SelectionSet Bagheera.ScalarCodecs.Id Bagheera.Object.Link
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Bagheera.ScalarCodecs.codecs |> Bagheera.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| Destination URL
-}
url : SelectionSet String Bagheera.Object.Link
url =
    Object.selectionForField "String" "url" [] Decode.string
