-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Bagheera.Object.LinkConnection exposing (..)

import Bagheera.Object
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


edges :
    SelectionSet decodesTo Bagheera.Object.LinkEdge
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Bagheera.Object.LinkConnection
edges object____ =
    Object.selectionForCompositeField "edges" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)


pageInfo :
    SelectionSet decodesTo Bagheera.Object.PageInfo
    -> SelectionSet decodesTo Bagheera.Object.LinkConnection
pageInfo object____ =
    Object.selectionForCompositeField "pageInfo" [] object____ Basics.identity
