-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Bagheera.Object.Link exposing (..)

import Bagheera.InputObject
import Bagheera.Interface
import Bagheera.Object
import Bagheera.Scalar
import Bagheera.ScalarCodecs
import Bagheera.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Auto-generated hash for the shortened URL
-}
hash : SelectionSet (Maybe String) Bagheera.Object.Link
hash =
    Object.selectionForField "(Maybe String)" "hash" [] (Decode.string |> Decode.nullable)


{-| All instances that a link has been viewed
-}
hits : SelectionSet (Maybe Int) Bagheera.Object.Link
hits =
    Object.selectionForField "(Maybe Int)" "hits" [] (Decode.int |> Decode.nullable)


{-| The ID of an object
-}
id : SelectionSet Bagheera.ScalarCodecs.Id Bagheera.Object.Link
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Bagheera.ScalarCodecs.codecs |> Bagheera.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| Destination URL
-}
url : SelectionSet (Maybe String) Bagheera.Object.Link
url =
    Object.selectionForField "(Maybe String)" "url" [] (Decode.string |> Decode.nullable)
