-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Bagheera.Object.Link exposing (..)

import Bagheera.Object
import Bagheera.Scalar
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ScalarCodecs


{-| Auto-generated hash for the shortened URL
-}
hash : SelectionSet String Bagheera.Object.Link
hash =
    Object.selectionForField "String" "hash" [] Decode.string


{-| The opaque ID of the link object
-}
id : SelectionSet ScalarCodecs.LinkId Bagheera.Object.Link
id =
    Object.selectionForField "ScalarCodecs.LinkId" "id" [] (ScalarCodecs.codecs |> Bagheera.Scalar.unwrapCodecs |> .codecLinkId |> .decoder)


{-| Destination URL
-}
url : SelectionSet String Bagheera.Object.Link
url =
    Object.selectionForField "String" "url" [] Decode.string


{-| Number of times a link has been viewed
-}
visits : SelectionSet (Maybe Int) Bagheera.Object.Link
visits =
    Object.selectionForField "(Maybe Int)" "visits" [] (Decode.int |> Decode.nullable)
