name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  preflight:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-21.05
          extra_nix_config: |
            extra-platforms = aarch64-linux

      - name: Install deps
        run: nix-shell --pure --run "make deps"

      - name: Compile
        run: |
          nix-shell --pure --run "elm make --output=/dev/null src/Main.elm"
          nix-shell --pure --run "cd review && elm make src/ReviewConfig.elm"
          nix-shell --pure --run "make elm-ports && make compile-ts"

      - name: Format
        run: |
          nix-shell --pure --run "elm-format src/ --validate"

      - name: Lint
        run: nix-shell --run "make lint"

      - name: Test
        run: nix-shell --run "make test"
